name: property_returns
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.13.4+2
  provider: ^4.0.0
  flutter_spinkit: ^4.1.1+1
  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.1
  flushbar:
  font_awesome_flutter: ^8.5.0
  flutter_markdown: ^0.3.4
  currency_pickers: ^1.0.6

dev_dependencies:
  pedantic: ^1.8.0+1
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/property_returns_logo.png"

flutter:
  uses-material-design: true

  assets:
  # - images/
    - assets/
    - assets/icon/property_returns_logo.png

  fonts:
   - family: Roboto
     fonts:
       - asset: fonts/Roboto/Roboto-Regular.ttf
