name: property_returns
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  provider: ^4.1.0
  flutter_spinkit: ^4.1.2
  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.1
  flushbar:
  font_awesome_flutter: ^8.8.1
  flutter_markdown: ^0.4.1
  currency_pickers: ^1.0.6
  flutter_phone_direct_caller: ^1.0.1
  email_validator: ^1.0.4
  string_validator: ^0.1.4
  flutter_email_sender: ^3.0.1  # for creating and sending an email
  url_launcher: ^5.4.5          # for opening the email client to write and send email
  google_fonts: ^1.0.0
  rxdart: ^0.24.1
#  firebase_messaging: ^6.0.9

dev_dependencies:
  pedantic: ^1.8.0+1
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/property_returns_logo.png"

flutter:
  uses-material-design: true

  assets:
  # - images/
    - assets/
    - assets/icon/property_returns_logo.png

#  fonts:
#   - family: Roboto
#     fonts:
#       - asset: fonts/Roboto/Roboto-Regular.ttf
